# JettraStore Explorer Configuration
app.title=JettraStore Explorer - Visual Cluster Manager
app.shorttitle=JSE
server.port=8088
server.contextpath=
app.language=es
app.theme=games

# Cluster & JettraStore Settings
jettra.cluster.name=Production-Store-Cluster
jettra.cluster.datacenter=DC-East-Loom
jettra.store.path=./data/store_explorer

# Security Credentials
security.admin.username=admin
security.admin.password=admin123
security.operator.username=operator
security.operator.password=operator123
