# JettraStudio Example Configuration
app.title=JettraStudio Pro Showcase
app.shorttitle=JS
server.port=8085
server.contextpath=
server.compactheader=true
server.session.timeout=1800
app.language=es
app.theme=games
app.animated=true
server.hotreload=true
server.typebackend=true
server.consoleshowregisterpage=false
app.roles=ADMIN,MANAGER,USER

# Admin Credentials for Demo
security.admin.username=admin
security.admin.password=admin123
security.demo.username=demo
security.demo.password=demo123
