app.title=Jettra Web 3D Future Dashboard
app.shorttitle=J
server.port=8080
server.contextpath=/jettrawebexample
server.compactheader=true
server.session.timeout=0
app.language=es
#app.theme=3d
app.theme=sai
app.animated=false
server.hotreload=true
baseUri=http://localhost:8080/jettrawebexample
# Backend Information
server.typebackend=false
server.backendpath=http://localhost:9002
jwt.juser= 65MhbQFLuR39ukAcrJTBRQ== 
jwt.jpassword=f7wdR7mDg1Js1jJcMLmnQUQ365mPgO2xlAry9KRGObIe5+rpJ05MEVQJ2LKLcv+LiSIKEYN6Sry8FuFLe7byNVQwZIowbo+c1wfaUrbv05s=